version: '3.9'

services:
  backend:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=chatdb
    depends_on:
      - postgres
    volumes:
      - .:/app
    command: npm run start:dev

  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8085:8080'

volumes:
  pgdata:
